name: Build release installers

on:
  push:
    branches:
        - master

env:
  build_directory: "Duplicati/GUI/Duplicati.GUI.TrayIcon/bin/Release"

jobs:
  zip_frontend:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Create artifacts directory
      run: |
        mkdir $HOME\artifacts
        cd Installer\Windows
        powershell -command "Compress-Archive -Path 'Frontend_Files' -DestinationPath '..\..\artifacts\frontend-files.zip'"
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: frontend-files
        path: $HOME\artifacts\frontend-files.zip

  windowsbuild:
    name: Windows Installer Build
    runs-on: windows-latest
    needs: zip_frontend
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: frontend-files
        path: $HOME\artifacts
      
  # debianbuild:
  #   name: Debian-like Installer          
  #   runs-on: ubuntu-latest
  #   needs: windowsbuild
  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v2

  #   - name: Download Windows Artifact
  #     uses: actions/download-artifact@v2
  #     with:
  #       name: build-results-windows
  #       path: $HOME/artifacts/windows

  #   - name: Build installers (Deb)
  #     run: |
  #       cd Installer/debian
  #       zipFile=$(find $HOME/artifacts/windows -name '*.zip' -exec basename {} \; | tail -n 1)
  #       sudo apt install debhelper
  #       ./artifact_deb.sh $HOME/artifacts/windows/$zipFile

  #   - name: Upload build results
  #     uses: actions/upload-artifact@v2
  #     with:
  #       retention-days: 5
  #       name: build-results-linux
  #       path: $HOME/artifacts


