# Build the project with the frontend files located in folder /Installer/Windows/Frontend_Files
# Windows builds
name: Zip Frontend Files and Upload Artifacts

on:
  workflow_dispatch

jobs:
  windowsbuild:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.3

      - name: Install NuGet
        uses: nuget/setup-nuget@v1.1.1

      - name: Download 7-Zip installer
        run: |
          # Download 7-Zip installer
          Invoke-WebRequest -Uri "https://www.7-zip.org/a/7z2301-src.7z" -OutFile "$env:TEMP\7zinstaller.msi"

      - name: Install 7-Zip
        run: |
          # Install 7-Zip silently
          Start-Process -Wait -FilePath msiexec -ArgumentList "/i $env:TEMP\7zinstaller.msi /quiet /qn /norestart"

      - name: Run artifact_win.bat with downloaded artifact
        run: |
          pushd Installer/Windows/Frontend_Files/
          7z a Frontend_Files.zip *
          popd
          .\\Installer\\Windows\\artifact_win.bat Frontend_Files/Frontend_Files.zip

      - name: Upload build results
        uses: actions/upload-artifact@v2
        with:
          retention-days: 5
          name: build-results-windows
          path: ~/artifacts/**/*
