name: Process Arguments

on:
  workflow_dispatch:
    inputs:
      num:
        description: number_of_clients
        required: true
        default: '2'
      server:
        description: 'Remote Server'
        required: true
        default: 'linux'

jobs:
  process_arguments:
    runs-on: ubuntu-latest
    steps:
      - name: Display Arguments
        run: |
          echo "Argument 1: ${{ github.event.inputs.num }}"
          echo "Argument 2: ${{ github.event.inputs.server }}"
