name: Build release installers

on:
  push:
    branches:
        - master

env:
  build_directory: "Duplicati/GUI/Duplicati.GUI.TrayIcon/bin/Release"

jobs:
  Installers:
    name: Installers
    runs-on: macos-latest
    strategy:
      fail-fast: false

    steps:
    - name: Install NuGet
      uses: nuget/setup-nuget@v1.1.1

    - name: Checkout Source
      uses: actions/checkout@v3

    - name: Restore NuGet Packages
      run: |
          nuget restore Duplicati.sln
          nuget restore "BuildTools/UpdateVersionStamp/UpdateVersionStamp.sln"


    - name: Build installers (OSX)
      run: |
          Installer/OSX/artifact_mac.sh

    - name: Upload build results
      uses: actions/upload-artifact@v3
      with:
        retention-days: 5
        name: build-results-mac
        path: ~/artifacts/**/*
