name: Zip Frontend Files and Upload Artifacts

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Zip Frontend Files
      run: zip -r Frontend_Files.zip Installer/Windows/Frontend_Files

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Frontend_Files_artifact
        path: Frontend_Files.zip